/**
 * Static data module — all CMA data and metrics hardcoded from official sources.
 *
 * Since we're deploying as a static export (Next.js output: "export"),
 * all data is embedded at build time. This module provides the canonical
 * data that the scoring algorithm, pages, and seed script all consume.
 */

import { CMA, Metric, MetricValue, RawMetricData } from "@/types";

// ── CMA Reference Data ───────────────────────────────────────────────────────

export const CMAS: CMA[] = [
  { id: "cma_toronto", name: "Toronto", slug: "toronto", province: "Ontario", provinceAbbr: "ON", populationLatest: 7109866, centroidLat: 43.7, centroidLng: -79.4, cmaBoundaryNote: "The Toronto CMA includes Mississauga, Brampton, Markham, Vaughan, Richmond Hill, and 20+ other municipalities." },
  { id: "cma_montreal", name: "Montréal", slug: "montreal", province: "Quebec", provinceAbbr: "QC", populationLatest: 4572813, centroidLat: 45.5, centroidLng: -73.6, cmaBoundaryNote: "The Montréal CMA includes Laval, Longueuil, and surrounding municipalities." },
  { id: "cma_vancouver", name: "Vancouver", slug: "vancouver", province: "British Columbia", provinceAbbr: "BC", populationLatest: 3081713, centroidLat: 49.3, centroidLng: -123.1, cmaBoundaryNote: "The Vancouver CMA includes Burnaby, Surrey, Richmond, Coquitlam, and the North Shore." },
  { id: "cma_calgary", name: "Calgary", slug: "calgary", province: "Alberta", provinceAbbr: "AB", populationLatest: 1783661, centroidLat: 51.0, centroidLng: -114.1, cmaBoundaryNote: "The Calgary CMA includes surrounding communities such as Airdrie and Cochrane." },
  { id: "cma_edmonton", name: "Edmonton", slug: "edmonton", province: "Alberta", provinceAbbr: "AB", populationLatest: 1641668, centroidLat: 53.5, centroidLng: -113.5, cmaBoundaryNote: "The Edmonton CMA includes Sherwood Park, St. Albert, Spruce Grove, and surrounding municipalities." },
  { id: "cma_ottawa", name: "Ottawa–Gatineau", slug: "ottawa-gatineau", province: "Ontario/Quebec", provinceAbbr: "ON/QC", populationLatest: 1661966, centroidLat: 45.4, centroidLng: -75.7, cmaBoundaryNote: "This bi-provincial CMA spans Ottawa (Ontario) and Gatineau (Quebec)." },
  { id: "cma_winnipeg", name: "Winnipeg", slug: "winnipeg", province: "Manitoba", provinceAbbr: "MB", populationLatest: 940010, centroidLat: 49.9, centroidLng: -97.1, cmaBoundaryNote: null },
  { id: "cma_quebec_city", name: "Québec City", slug: "quebec-city", province: "Quebec", provinceAbbr: "QC", populationLatest: 894691, centroidLat: 46.8, centroidLng: -71.2, cmaBoundaryNote: null },
  { id: "cma_hamilton", name: "Hamilton", slug: "hamilton", province: "Ontario", provinceAbbr: "ON", populationLatest: 862679, centroidLat: 43.3, centroidLng: -79.9, cmaBoundaryNote: null },
  { id: "cma_kitchener", name: "Kitchener–Cambridge–Waterloo", slug: "kitchener-cambridge-waterloo", province: "Ontario", provinceAbbr: "ON", populationLatest: 699402, centroidLat: 43.5, centroidLng: -80.5, cmaBoundaryNote: "This tri-city CMA covers Kitchener, Cambridge, Waterloo, and Woolwich Township." },
  { id: "cma_london", name: "London", slug: "london", province: "Ontario", provinceAbbr: "ON", populationLatest: 626875, centroidLat: 43.0, centroidLng: -81.3, cmaBoundaryNote: null },
  { id: "cma_halifax", name: "Halifax", slug: "halifax", province: "Nova Scotia", provinceAbbr: "NS", populationLatest: 536372, centroidLat: 44.6, centroidLng: -63.6, cmaBoundaryNote: null },
  { id: "cma_oshawa", name: "Oshawa", slug: "oshawa", province: "Ontario", provinceAbbr: "ON", populationLatest: 482076, centroidLat: 43.9, centroidLng: -78.9, cmaBoundaryNote: "The Oshawa CMA includes Whitby, Clarington, and other Durham Region municipalities." },
  { id: "cma_victoria", name: "Victoria", slug: "victoria", province: "British Columbia", provinceAbbr: "BC", populationLatest: 441961, centroidLat: 48.4, centroidLng: -123.4, cmaBoundaryNote: null },
  { id: "cma_windsor", name: "Windsor", slug: "windsor", province: "Ontario", provinceAbbr: "ON", populationLatest: 484698, centroidLat: 42.3, centroidLng: -83.0, cmaBoundaryNote: null },
  { id: "cma_saskatoon", name: "Saskatoon", slug: "saskatoon", province: "Saskatchewan", provinceAbbr: "SK", populationLatest: 369766, centroidLat: 52.1, centroidLng: -106.7, cmaBoundaryNote: null },
  { id: "cma_regina", name: "Regina", slug: "regina", province: "Saskatchewan", provinceAbbr: "SK", populationLatest: 285039, centroidLat: 50.4, centroidLng: -104.6, cmaBoundaryNote: null },
  { id: "cma_sherbrooke", name: "Sherbrooke", slug: "sherbrooke", province: "Quebec", provinceAbbr: "QC", populationLatest: 242136, centroidLat: 45.4, centroidLng: -71.9, cmaBoundaryNote: null },
  { id: "cma_barrie", name: "Barrie", slug: "barrie", province: "Ontario", provinceAbbr: "ON", populationLatest: 247098, centroidLat: 44.4, centroidLng: -79.7, cmaBoundaryNote: null },
  { id: "cma_kelowna", name: "Kelowna", slug: "kelowna", province: "British Columbia", provinceAbbr: "BC", populationLatest: 251648, centroidLat: 49.9, centroidLng: -119.5, cmaBoundaryNote: null },
  { id: "cma_abbotsford", name: "Abbotsford–Mission", slug: "abbotsford-mission", province: "British Columbia", provinceAbbr: "BC", populationLatest: 220638, centroidLat: 49.1, centroidLng: -122.3, cmaBoundaryNote: null },
  { id: "cma_sudbury", name: "Greater Sudbury", slug: "greater-sudbury", province: "Ontario", provinceAbbr: "ON", populationLatest: 192688, centroidLat: 46.5, centroidLng: -81.0, cmaBoundaryNote: null },
  { id: "cma_kingston", name: "Kingston", slug: "kingston", province: "Ontario", provinceAbbr: "ON", populationLatest: 192395, centroidLat: 44.2, centroidLng: -76.5, cmaBoundaryNote: null },
  { id: "cma_saguenay", name: "Saguenay", slug: "saguenay", province: "Quebec", provinceAbbr: "QC", populationLatest: 169247, centroidLat: 48.4, centroidLng: -71.1, cmaBoundaryNote: null },
  { id: "cma_thunder_bay", name: "Thunder Bay", slug: "thunder-bay", province: "Ontario", provinceAbbr: "ON", populationLatest: 133305, centroidLat: 48.4, centroidLng: -89.2, cmaBoundaryNote: null },
  { id: "cma_saint_john", name: "Saint John", slug: "saint-john", province: "New Brunswick", provinceAbbr: "NB", populationLatest: 142905, centroidLat: 45.3, centroidLng: -66.1, cmaBoundaryNote: null },
  { id: "cma_fredericton", name: "Fredericton", slug: "fredericton", province: "New Brunswick", provinceAbbr: "NB", populationLatest: 123308, centroidLat: 45.9, centroidLng: -66.6, cmaBoundaryNote: null },
  { id: "cma_moncton", name: "Moncton", slug: "moncton", province: "New Brunswick", provinceAbbr: "NB", populationLatest: 190477, centroidLat: 46.1, centroidLng: -64.8, cmaBoundaryNote: null },
  { id: "cma_guelph", name: "Guelph", slug: "guelph", province: "Ontario", provinceAbbr: "ON", populationLatest: 182615, centroidLat: 43.5, centroidLng: -80.2, cmaBoundaryNote: null },
  { id: "cma_brantford", name: "Brantford", slug: "brantford", province: "Ontario", provinceAbbr: "ON", populationLatest: 173380, centroidLat: 43.1, centroidLng: -80.3, cmaBoundaryNote: null },
  { id: "cma_peterborough", name: "Peterborough", slug: "peterborough", province: "Ontario", provinceAbbr: "ON", populationLatest: 148630, centroidLat: 44.3, centroidLng: -78.3, cmaBoundaryNote: null },
  { id: "cma_lethbridge", name: "Lethbridge", slug: "lethbridge", province: "Alberta", provinceAbbr: "AB", populationLatest: 140181, centroidLat: 49.7, centroidLng: -112.8, cmaBoundaryNote: null },
  { id: "cma_nanaimo", name: "Nanaimo", slug: "nanaimo", province: "British Columbia", provinceAbbr: "BC", populationLatest: 128285, centroidLat: 49.2, centroidLng: -124.0, cmaBoundaryNote: null },
  { id: "cma_red_deer", name: "Red Deer", slug: "red-deer", province: "Alberta", provinceAbbr: "AB", populationLatest: 112959, centroidLat: 52.3, centroidLng: -113.8, cmaBoundaryNote: null },
  { id: "cma_trois_rivieres", name: "Trois-Rivières", slug: "trois-rivieres", province: "Quebec", provinceAbbr: "QC", populationLatest: 172585, centroidLat: 46.4, centroidLng: -72.5, cmaBoundaryNote: null },
  { id: "cma_st_johns", name: "St. John's", slug: "st-johns", province: "Newfoundland and Labrador", provinceAbbr: "NL", populationLatest: 240428, centroidLat: 47.56, centroidLng: -52.71, cmaBoundaryNote: "The St. John's CMA includes Mount Pearl, Paradise, Conception Bay South, and surrounding municipalities on the Avalon Peninsula." },
];

// ── Metric Definitions ───────────────────────────────────────────────────────

export const METRICS: Metric[] = [
  // Economic Vitality
  {
    id: "metric_unemployment_rate",
    dimension: "economic",
    name: "Unemployment Rate",
    description: null,
    sourceName: "Statistics Canada Labour Force Survey",
    sourceTable: "14-10-0459-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410045901",
    updateFrequency: "Monthly",
    direction: "lower_is_better",
    weightWithinDimension: 40,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_employment_rate",
    dimension: "economic",
    name: "Employment Rate",
    description: null,
    sourceName: "Statistics Canada Labour Force Survey",
    sourceTable: "14-10-0459-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410045901",
    updateFrequency: "Monthly",
    direction: "higher_is_better",
    weightWithinDimension: 30,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_median_income",
    dimension: "economic",
    name: "Median Household Income",
    description: null,
    sourceName: "Statistics Canada T1FF / Census",
    sourceTable: "11-10-0162-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1110016201",
    updateFrequency: "Annual (18-month lag)",
    direction: "higher_is_better",
    weightWithinDimension: 30,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  // Housing Affordability
  {
    id: "metric_avg_rent",
    dimension: "housing",
    name: "Average Monthly Rent (2BR)",
    description: null,
    sourceName: "CMHC Rental Market Survey",
    sourceTable: null,
    sourceUrl: "https://www.cmhc-schl.gc.ca/en/professionals/housing-markets-data-and-research/housing-data/data-tables/rental-market",
    updateFrequency: "Annual",
    direction: "lower_is_better",
    weightWithinDimension: 30,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_vacancy_rate",
    dimension: "housing",
    name: "Rental Vacancy Rate",
    description: null,
    sourceName: "CMHC Rental Market Survey",
    sourceTable: null,
    sourceUrl: "https://www.cmhc-schl.gc.ca/en/professionals/housing-markets-data-and-research/housing-data/data-tables/rental-market",
    updateFrequency: "Annual",
    direction: "higher_is_better",
    weightWithinDimension: 20,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_housing_price_index",
    dimension: "housing",
    name: "New Housing Price Index",
    description: "Measures price change since Dec 2016 (base = 100), not absolute prices. A value of 108 means prices rose 8% since 2016.",
    sourceName: "CMHC / Statistics Canada (CREA HPI proxy)",
    sourceTable: "18-10-0205-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810020501",
    updateFrequency: "Monthly",
    direction: "lower_is_better",
    weightWithinDimension: 25,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_avg_home_price",
    dimension: "housing",
    name: "Average New Home Price",
    description: null,
    sourceName: "CMHC Absorbed Unit Prices",
    sourceTable: null,
    sourceUrl: "https://www.cmhc-schl.gc.ca/en/professionals/housing-markets-data-and-research/housing-data/data-tables/starts-completions-absorbed",
    updateFrequency: "Quarterly",
    direction: "lower_is_better",
    weightWithinDimension: 25,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  // Quality of Life
  {
    id: "metric_cpi",
    dimension: "quality_of_life",
    name: "Consumer Price Index",
    description: "Measures inflation since 2002 (base = 100), not cost of living. Higher = faster price increases.",
    sourceName: "Statistics Canada CPI",
    sourceTable: "18-10-0004-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401",
    updateFrequency: "Monthly (12 cities; provincial fallback)",
    direction: "lower_is_better",
    weightWithinDimension: 40,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_pop_growth",
    dimension: "quality_of_life",
    name: "5-Year Population Growth Rate",
    description: null,
    sourceName: "Statistics Canada Population Estimates",
    sourceTable: "17-10-0148-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710014801",
    updateFrequency: "Annual",
    direction: "higher_is_better",
    weightWithinDimension: 60,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  // Safety
  {
    id: "metric_csi",
    dimension: "safety",
    name: "Crime Severity Index",
    description: "Weighted crime index where serious crimes count more. Canada-wide base = 100 in 2006.",
    sourceName: "Statistics Canada Uniform Crime Reporting Survey",
    sourceTable: "35-10-0026-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3510002601",
    updateFrequency: "Annual (7-month lag)",
    direction: "lower_is_better",
    weightWithinDimension: 100,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  // Environment
  {
    id: "metric_aqhi",
    dimension: "environment",
    name: "Air Quality Health Index (30-day avg)",
    description: null,
    sourceName: "Environment and Climate Change Canada",
    sourceTable: null,
    sourceUrl: "https://www.canada.ca/en/environment-climate-change/services/air-quality-health-index.html",
    updateFrequency: "Daily (30-day rolling average shown)",
    direction: "lower_is_better",
    weightWithinDimension: 100,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  // Demographics
  {
    id: "metric_population",
    dimension: "demographics",
    name: "Population",
    description: null,
    sourceName: "Statistics Canada Population Estimates",
    sourceTable: "17-10-0148-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710014801",
    updateFrequency: "Annual",
    direction: "neutral",
    weightWithinDimension: 0,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_pop_growth_5yr",
    dimension: "demographics",
    name: "5-Year Population Growth",
    description: null,
    sourceName: "Statistics Canada Population Estimates",
    sourceTable: "17-10-0148-01",
    sourceUrl: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710014801",
    updateFrequency: "Annual",
    direction: "higher_is_better",
    weightWithinDimension: 50,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_immigration_share",
    dimension: "demographics",
    name: "Immigration Share",
    description: null,
    sourceName: "Statistics Canada Census 2021",
    sourceTable: "98-10-0384-01",
    sourceUrl: "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/index.cfm",
    updateFrequency: "5-year Census",
    direction: "higher_is_better",
    weightWithinDimension: 30,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
  {
    id: "metric_median_age",
    dimension: "demographics",
    name: "Median Age",
    description: null,
    sourceName: "Statistics Canada Census 2021",
    sourceTable: "98-10-0384-01",
    sourceUrl: "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/index.cfm",
    updateFrequency: "5-year Census",
    direction: "neutral",
    weightWithinDimension: 0,
    proxyFallbackMetricId: null,
    isProxyTarget: false,
  },
];

// ── Raw Metric Values ────────────────────────────────────────────────────────
// Period: "2026-01" for January 2026 monthly data, "2024" for annual 2024 data,
// "2022" for 2022 T1FF income data, "2021" for Census 2021 data
// Last updated by scripts/ingest-data.ts on 2026-02-28

type MetricValueInput = {
  cmaId: string;
  metricId: string;
  period: string;
  value: number | null;
  isProxy: boolean;
  proxyNote: string | null;
  sourcePublicationDate: string;
  sourceTableId: string | null;
};

export const RAW_METRIC_VALUES: MetricValueInput[] = [
  // ── Unemployment Rate (January 2026, seasonally adjusted) ──
  // Source: StatsCan Table 14-10-0459-01, LFS January 2026 release (2026-02-07)
  ...([
    ["cma_toronto", 7.9],
    ["cma_montreal", 6.1],
    ["cma_vancouver", 6.3],
    ["cma_calgary", 6.7],
    ["cma_edmonton", 6.8],
    ["cma_ottawa", 7],
    ["cma_winnipeg", 6.3],
    ["cma_quebec_city", 3],
    ["cma_hamilton", 7.4],
    ["cma_kitchener", 8.3],
    ["cma_london", 8.2],
    ["cma_halifax", 5.8],
    ["cma_oshawa", 8.1],
    ["cma_victoria", 4.4],
    ["cma_windsor", 8.1],
    ["cma_saskatoon", 6],
    ["cma_regina", 7.2],
    ["cma_sherbrooke", 5.1],
    ["cma_barrie", 8.3],
    ["cma_kelowna", 6.8],
    ["cma_abbotsford", 6.3],
    ["cma_sudbury", 6.7],
    ["cma_kingston", 6],
    ["cma_saguenay", 4.1],
    ["cma_thunder_bay", 4.6],
    ["cma_saint_john", 5.6],
    ["cma_fredericton", 5.8],
    ["cma_moncton", 5.6],
    ["cma_guelph", 7],
    ["cma_brantford", 8.7],
    ["cma_peterborough", 6.6],
    ["cma_lethbridge", 7.4],
    ["cma_nanaimo", 6.6],
    ["cma_red_deer", 8.1],
    ["cma_trois_rivieres", 3.9],
    ["cma_st_johns", 7.7]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_unemployment_rate",
    period: "2026-01",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2026-02-07",
    sourceTableId: "14-10-0459-01",
  })),

  // ── Employment Rate (January 2026, seasonally adjusted) ──
  // Source: StatsCan Table 14-10-0459-01, LFS January 2026 release (2026-02-07)
  ...([
    ["cma_toronto", 61.3],
    ["cma_montreal", 62.5],
    ["cma_vancouver", 62.5],
    ["cma_calgary", 64.8],
    ["cma_edmonton", 64.6],
    ["cma_ottawa", 61.5],
    ["cma_winnipeg", 63.9],
    ["cma_quebec_city", 68.1],
    ["cma_hamilton", 60.8],
    ["cma_kitchener", 64.7],
    ["cma_london", 60.6],
    ["cma_halifax", 64],
    ["cma_oshawa", 62.2],
    ["cma_victoria", 62.9],
    ["cma_windsor", 59.4],
    ["cma_saskatoon", 66.4],
    ["cma_regina", 65.5],
    ["cma_sherbrooke", 59.2],
    ["cma_barrie", 63.3],
    ["cma_kelowna", 61.8],
    ["cma_abbotsford", 62.8],
    ["cma_sudbury", 59.6],
    ["cma_kingston", 58.6],
    ["cma_saguenay", 57],
    ["cma_thunder_bay", 63.2],
    ["cma_saint_john", 54.2],
    ["cma_fredericton", 63.6],
    ["cma_moncton", 62.6],
    ["cma_guelph", 61.9],
    ["cma_brantford", 60.7],
    ["cma_peterborough", 55.3],
    ["cma_lethbridge", 61.7],
    ["cma_nanaimo", 57.9],
    ["cma_red_deer", 62.1],
    ["cma_trois_rivieres", 59.9],
    ["cma_st_johns", 60.6]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_employment_rate",
    period: "2026-01",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2026-02-07",
    sourceTableId: "14-10-0459-01",
  })),

  // ── Median Household Income 2022 (T1FF) ──
  // Source: StatsCan income statistics, 2022 tax year (latest available as of early 2026)
  ...([
    ["cma_toronto", 92000],
    ["cma_montreal", 76000],
    ["cma_vancouver", 89000],
    ["cma_calgary", 102000],
    ["cma_edmonton", 96000],
    ["cma_ottawa", 104000],
    ["cma_winnipeg", 88000],
    ["cma_quebec_city", 83000],
    ["cma_hamilton", 89000],
    ["cma_kitchener", 96000],
    ["cma_london", 83000],
    ["cma_halifax", 88000],
    ["cma_oshawa", 97000],
    ["cma_victoria", 91000],
    ["cma_windsor", 83000],
    ["cma_saskatoon", 92000],
    ["cma_regina", 91000],
    ["cma_sherbrooke", 73000],
    ["cma_barrie", 93000],
    ["cma_kelowna", 87000],
    ["cma_abbotsford", 82000],
    ["cma_sudbury", 87000],
    ["cma_kingston", 86000],
    ["cma_saguenay", 74000],
    ["cma_thunder_bay", 83000],
    ["cma_saint_john", 76000],
    ["cma_fredericton", 82000],
    ["cma_moncton", 81000],
    ["cma_guelph", 98000],
    ["cma_brantford", 86000],
    ["cma_peterborough", 82000],
    ["cma_lethbridge", 90000],
    ["cma_nanaimo", 81000],
    ["cma_red_deer", 94000],
    ["cma_trois_rivieres", 72000],
    ["cma_st_johns", 80000]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_median_income",
    period: "2022",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2024-09-18",
    sourceTableId: "11-10-0162-01",
  })),

  // ── Average Monthly Rent 2BR (2024 CMHC Rental Market Survey) ──
  // Source: CMHC Rental Market Survey, October 2024 survey, published January 28, 2025
  ...([
    ["cma_toronto", 2034],
    ["cma_montreal", 1279],
    ["cma_vancouver", 2548],
    ["cma_calgary", 1953],
    ["cma_edmonton", 1531],
    ["cma_ottawa", 1874],
    ["cma_winnipeg", 1432],
    ["cma_quebec_city", 1108],
    ["cma_hamilton", 1756],
    ["cma_kitchener", 1864],
    ["cma_london", 1589],
    ["cma_halifax", 1967],
    ["cma_oshawa", 1912],
    ["cma_victoria", 2253],
    ["cma_windsor", 1476],
    ["cma_saskatoon", 1347],
    ["cma_regina", 1264],
    ["cma_sherbrooke", 917],
    ["cma_barrie", 1872],
    ["cma_kelowna", 1958],
    ["cma_abbotsford", 1812],
    ["cma_sudbury", 1198],
    ["cma_kingston", 1678],
    ["cma_saguenay", 924],
    ["cma_thunder_bay", 1165],
    ["cma_saint_john", 1198],
    ["cma_fredericton", 1254],
    ["cma_moncton", 1373],
    ["cma_guelph", 1946],
    ["cma_brantford", 1574],
    ["cma_peterborough", 1543],
    ["cma_lethbridge", 1263],
    ["cma_nanaimo", 1878],
    ["cma_red_deer", 1278],
    ["cma_trois_rivieres", 978],
    ["cma_st_johns", 1483]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_avg_rent",
    period: "2024",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2025-01-28",
    sourceTableId: null,
  })),

  // ── Rental Vacancy Rate (2024 CMHC Rental Market Survey) ──
  // Source: CMHC Rental Market Survey, October 2024 survey, published January 28, 2025
  ...([
    ["cma_toronto", 3],
    ["cma_montreal", 3.1],
    ["cma_vancouver", 1.1],
    ["cma_calgary", 2.8],
    ["cma_edmonton", 3],
    ["cma_ottawa", 2.2],
    ["cma_winnipeg", 3.2],
    ["cma_quebec_city", 2.7],
    ["cma_hamilton", 1.8],
    ["cma_kitchener", 2.1],
    ["cma_london", 1.7],
    ["cma_halifax", 1.3],
    ["cma_oshawa", 1.6],
    ["cma_victoria", 1.6],
    ["cma_windsor", 2.4],
    ["cma_saskatoon", 3.9],
    ["cma_regina", 4.6],
    ["cma_sherbrooke", 4.2],
    ["cma_barrie", 2.3],
    ["cma_kelowna", 1.6],
    ["cma_abbotsford", 1.8],
    ["cma_sudbury", 5.6],
    ["cma_kingston", 2.5],
    ["cma_saguenay", 3.5],
    ["cma_thunder_bay", 5.2],
    ["cma_saint_john", 4.1],
    ["cma_fredericton", 3.5],
    ["cma_moncton", 2.9],
    ["cma_guelph", 2.1],
    ["cma_brantford", 2.2],
    ["cma_peterborough", 2.6],
    ["cma_lethbridge", 5.1],
    ["cma_nanaimo", 2.3],
    ["cma_red_deer", 5.8],
    ["cma_trois_rivieres", 4.4],
    ["cma_st_johns", 4.2]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_vacancy_rate",
    period: "2024",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2025-01-28",
    sourceTableId: null,
  })),

  // ── New Housing Price Index January 2026 (StatsCan Table 18-10-0205-01) ──
  // Source: StatsCan Table 18-10-0205-01, January 2026 data (base Dec 2016=100)
  ...([
    ["cma_toronto", 108.1, false, null],
    ["cma_montreal", 158.8, false, null],
    ["cma_vancouver", 125, false, null],
    ["cma_calgary", 129.7, false, null],
    ["cma_edmonton", 104.7, false, null],
    ["cma_ottawa", 161, false, null],
    ["cma_winnipeg", 145.4, false, null],
    ["cma_quebec_city", 143.1, false, null],
    ["cma_hamilton", 109.1, false, null],
    ["cma_kitchener", 153, false, null],
    ["cma_london", 137.9, false, null],
    ["cma_halifax", 127.5, false, null],
    ["cma_oshawa", 116.9, false, null],
    ["cma_victoria", 121.9, false, null],
    ["cma_windsor", 144.5, false, null],
    ["cma_saskatoon", 111.9, false, null],
    ["cma_regina", 106.9, false, null],
    ["cma_sherbrooke", 112.1, false, null],
    ["cma_barrie", 119.4, true, "Ontario provincial NHPI used as proxy"],
    ["cma_kelowna", 118.4, false, null],
    ["cma_abbotsford", 124.3, true, "BC provincial NHPI used as proxy"],
    ["cma_sudbury", 118.9, false, null],
    ["cma_kingston", 119.4, true, "Ontario provincial NHPI used as proxy"],
    ["cma_saguenay", 149.3, true, "Quebec provincial NHPI used as proxy"],
    ["cma_thunder_bay", 119.4, true, "Ontario provincial NHPI used as proxy"],
    ["cma_saint_john", 120.7, false, null],
    ["cma_fredericton", 120.7, false, null],
    ["cma_moncton", 120.7, false, null],
    ["cma_guelph", 120.7, false, null],
    ["cma_brantford", 119.4, true, "Ontario provincial NHPI used as proxy"],
    ["cma_peterborough", 119.4, true, "Ontario provincial NHPI used as proxy"],
    ["cma_lethbridge", 118, true, "Alberta provincial NHPI used as proxy"],
    ["cma_nanaimo", 124.3, true, "BC provincial NHPI used as proxy"],
    ["cma_red_deer", 118, true, "Alberta provincial NHPI used as proxy"],
    ["cma_trois_rivieres", 119.6, false, null],
    ["cma_st_johns", 109.8, false, null]
  ] as [string, number | null, boolean, string | null][]).map(([cmaId, value, isProxy, proxyNote]) => ({
    cmaId,
    metricId: "metric_housing_price_index",
    period: "2026-01",
    value: value as number | null,
    isProxy: isProxy as boolean,
    proxyNote: proxyNote as string | null,
    sourcePublicationDate: "2026-02-20",
    sourceTableId: "18-10-0205-01",
  })),

  // ── Consumer Price Index January 2026 (StatsCan Table 18-10-0004-01) ──
  // Source: StatsCan Table 18-10-0004-01, January 2026 (2002=100 base). ~15 direct cities; others use provincial proxy.
  ...([
    ["cma_toronto", 167.7, false, null],
    ["cma_montreal", 165.3, false, null],
    ["cma_vancouver", 161.9, false, null],
    ["cma_calgary", 176.6, false, null],
    ["cma_edmonton", 171.5, false, null],
    ["cma_ottawa", 167, false, null],
    ["cma_winnipeg", 165.7, false, null],
    ["cma_quebec_city", 160.5, false, null],
    ["cma_hamilton", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_kitchener", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_london", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_halifax", 167.7, false, null],
    ["cma_oshawa", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_victoria", 156.2, false, null],
    ["cma_windsor", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_saskatoon", 168.2, false, null],
    ["cma_regina", 168.1, false, null],
    ["cma_sherbrooke", 162.3, true, "Quebec provincial CPI used as proxy"],
    ["cma_barrie", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_kelowna", 159.1, true, "BC provincial CPI used as proxy"],
    ["cma_abbotsford", 159.1, true, "BC provincial CPI used as proxy"],
    ["cma_sudbury", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_kingston", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_saguenay", 162.3, true, "Quebec provincial CPI used as proxy"],
    ["cma_thunder_bay", 154.9, false, null],
    ["cma_saint_john", 164.8, false, null],
    ["cma_fredericton", 164.6, true, "New Brunswick provincial CPI used as proxy"],
    ["cma_moncton", 164.6, true, "New Brunswick provincial CPI used as proxy"],
    ["cma_guelph", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_brantford", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_peterborough", 165.9, true, "Ontario provincial CPI used as proxy"],
    ["cma_lethbridge", 173.5, true, "Alberta provincial CPI used as proxy"],
    ["cma_nanaimo", 159.1, true, "BC provincial CPI used as proxy"],
    ["cma_red_deer", 173.5, true, "Alberta provincial CPI used as proxy"],
    ["cma_trois_rivieres", 162.3, true, "Quebec provincial CPI used as proxy"],
    ["cma_st_johns", 164.3, false, null]
  ] as [string, number | null, boolean, string | null][]).map(([cmaId, value, isProxy, proxyNote]) => ({
    cmaId,
    metricId: "metric_cpi",
    period: "2026-01",
    value: value as number | null,
    isProxy: isProxy as boolean,
    proxyNote: proxyNote as string | null,
    sourcePublicationDate: "2026-02-18",
    sourceTableId: "18-10-0004-01",
  })),

  // ── 5-Year Population Growth Rate 2019-2024 ──
  // Source: StatsCan Table 17-10-0148-01, July 2024 estimates. Growth: (pop2024-pop2019)/pop2019*100
  ...([
    ["cma_toronto", 10.6],
    ["cma_montreal", 5.7],
    ["cma_vancouver", 13.5],
    ["cma_calgary", 18.7],
    ["cma_edmonton", 14.1],
    ["cma_ottawa", 11],
    ["cma_winnipeg", 11],
    ["cma_quebec_city", 7.4],
    ["cma_hamilton", 7.9],
    ["cma_kitchener", 20],
    ["cma_london", 14.2],
    ["cma_halifax", 15.9],
    ["cma_oshawa", 16.4],
    ["cma_victoria", 9.4],
    ["cma_windsor", 11.7],
    ["cma_saskatoon", 14.3],
    ["cma_regina", 11.1],
    ["cma_sherbrooke", 8.9],
    ["cma_barrie", 15.2],
    ["cma_kelowna", 14.1],
    ["cma_abbotsford", 9.3],
    ["cma_sudbury", 9.9],
    ["cma_kingston", 9.1],
    ["cma_saguenay", 4.5],
    ["cma_thunder_bay", 3.9],
    ["cma_saint_john", 8.8],
    ["cma_fredericton", 13],
    ["cma_moncton", 22.8],
    ["cma_guelph", 9.2],
    ["cma_brantford", 14.9],
    ["cma_peterborough", 12.8],
    ["cma_lethbridge", 11.4],
    ["cma_nanaimo", 9.6],
    ["cma_red_deer", 8.3],
    ["cma_trois_rivieres", 8.3],
    ["cma_st_johns", 10.4]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_pop_growth",
    period: "2024",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2025-01-16",
    sourceTableId: "17-10-0148-01",
  })),

  // ── Crime Severity Index 2024 ──
  // Source: StatsCan Table 35-10-0026-01, 2024 UCR data published July 22, 2025
  ...([
    ["cma_toronto", 59.35, false, null],
    ["cma_montreal", 61.67, false, null],
    ["cma_vancouver", 81.2, false, null],
    ["cma_calgary", 62.32, false, null],
    ["cma_edmonton", 101.12, false, null],
    ["cma_ottawa", 55.42, false, null],
    ["cma_winnipeg", 124.41, false, null],
    ["cma_quebec_city", 55.32, false, null],
    ["cma_hamilton", 58.28, false, null],
    ["cma_kitchener", 72.68, false, null],
    ["cma_london", 61.22, false, null],
    ["cma_halifax", 73.95, false, null],
    ["cma_oshawa", 60.69, true, "Ontario provincial CSI used as proxy (Oshawa CMA not in 2024 table)"],
    ["cma_victoria", 71.04, false, null],
    ["cma_windsor", 63.16, false, null],
    ["cma_saskatoon", 106.71, false, null],
    ["cma_regina", 100.31, false, null],
    ["cma_sherbrooke", 53.9, false, null],
    ["cma_barrie", 48.1, false, null],
    ["cma_kelowna", 108.82, false, null],
    ["cma_abbotsford", 94.96, false, null],
    ["cma_sudbury", 66.36, false, null],
    ["cma_kingston", 59.26, false, null],
    ["cma_saguenay", 55.11, false, null],
    ["cma_thunder_bay", 107.7, false, null],
    ["cma_saint_john", 58.4, false, null],
    ["cma_fredericton", 73.61, false, null],
    ["cma_moncton", 93.83, false, null],
    ["cma_guelph", 56, false, null],
    ["cma_brantford", 70.71, false, null],
    ["cma_peterborough", 61.3, false, null],
    ["cma_lethbridge", 105.51, false, null],
    ["cma_nanaimo", 106.71, false, null],
    ["cma_red_deer", 118.65, false, null],
    ["cma_trois_rivieres", 61.2, false, null],
    ["cma_st_johns", 76.95, false, null]
  ] as [string, number | null, boolean, string | null][]).map(([cmaId, value, isProxy, proxyNote]) => ({
    cmaId,
    metricId: "metric_csi",
    period: "2024",
    value: value as number | null,
    isProxy: isProxy as boolean,
    proxyNote: proxyNote as string | null,
    sourcePublicationDate: "2025-07-22",
    sourceTableId: "35-10-0026-01",
  })),

  // ── AQHI 30-day rolling average (January 2026) ──
  // Source: Environment and Climate Change Canada AQHI monitoring stations, winter 2025-26 seasonal averages
  ...([
    ["cma_toronto", 2.9],
    ["cma_montreal", 2.6],
    ["cma_vancouver", 2.8],
    ["cma_calgary", 2.2],
    ["cma_edmonton", 2.5],
    ["cma_ottawa", 2.4],
    ["cma_winnipeg", 2.1],
    ["cma_quebec_city", 2],
    ["cma_hamilton", 3.1],
    ["cma_kitchener", 2.7],
    ["cma_london", 2.6],
    ["cma_halifax", 2.1],
    ["cma_oshawa", 3],
    ["cma_victoria", 2.2],
    ["cma_windsor", 3.3],
    ["cma_saskatoon", 2.5],
    ["cma_regina", 2.3],
    ["cma_sherbrooke", 2.1],
    ["cma_barrie", 2.4],
    ["cma_kelowna", 2.6],
    ["cma_abbotsford", 2.9],
    ["cma_sudbury", 2.2],
    ["cma_kingston", 2.3],
    ["cma_saguenay", 2],
    ["cma_thunder_bay", 2.3],
    ["cma_saint_john", 2.1],
    ["cma_fredericton", 2.2],
    ["cma_moncton", 2.1],
    ["cma_guelph", 2.6],
    ["cma_brantford", 2.8],
    ["cma_peterborough", 2.4],
    ["cma_lethbridge", 2.3],
    ["cma_nanaimo", 2.3],
    ["cma_red_deer", 2.5],
    ["cma_trois_rivieres", 2],
    ["cma_st_johns", 1.9]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_aqhi",
    period: "2026-01",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2026-01-27",
    sourceTableId: null,
  })),

  // ── Population 2024 (for display) ──
  // Source: StatsCan Table 17-10-0148-01, July 2024 estimates published January 16, 2025
  ...([
    ["cma_toronto", 7109866],
    ["cma_montreal", 4572813],
    ["cma_vancouver", 3081713],
    ["cma_calgary", 1783661],
    ["cma_edmonton", 1641668],
    ["cma_ottawa", 1661966],
    ["cma_winnipeg", 940010],
    ["cma_quebec_city", 894691],
    ["cma_hamilton", 862679],
    ["cma_kitchener", 699402],
    ["cma_london", 626875],
    ["cma_halifax", 536372],
    ["cma_oshawa", 482076],
    ["cma_victoria", 441961],
    ["cma_windsor", 484698],
    ["cma_saskatoon", 369766],
    ["cma_regina", 285039],
    ["cma_sherbrooke", 242136],
    ["cma_barrie", 247098],
    ["cma_kelowna", 251648],
    ["cma_abbotsford", 220638],
    ["cma_sudbury", 192688],
    ["cma_kingston", 192395],
    ["cma_saguenay", 169247],
    ["cma_thunder_bay", 133305],
    ["cma_saint_john", 142905],
    ["cma_fredericton", 123308],
    ["cma_moncton", 190477],
    ["cma_guelph", 182615],
    ["cma_brantford", 173380],
    ["cma_peterborough", 148630],
    ["cma_lethbridge", 140181],
    ["cma_nanaimo", 128285],
    ["cma_red_deer", 112959],
    ["cma_trois_rivieres", 172585],
    ["cma_st_johns", 240428]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_population",
    period: "2024",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2025-01-16",
    sourceTableId: "17-10-0148-01",
  })),

  // ── 5-Year Population Growth (demographics dimension) ──
  // Source: StatsCan Table 17-10-0148-01, July 2024 estimates. Growth: (pop2024-pop2019)/pop2019*100
  ...([
    ["cma_toronto", 10.6],
    ["cma_montreal", 5.7],
    ["cma_vancouver", 13.5],
    ["cma_calgary", 18.7],
    ["cma_edmonton", 14.1],
    ["cma_ottawa", 11],
    ["cma_winnipeg", 11],
    ["cma_quebec_city", 7.4],
    ["cma_hamilton", 7.9],
    ["cma_kitchener", 20],
    ["cma_london", 14.2],
    ["cma_halifax", 15.9],
    ["cma_oshawa", 16.4],
    ["cma_victoria", 9.4],
    ["cma_windsor", 11.7],
    ["cma_saskatoon", 14.3],
    ["cma_regina", 11.1],
    ["cma_sherbrooke", 8.9],
    ["cma_barrie", 15.2],
    ["cma_kelowna", 14.1],
    ["cma_abbotsford", 9.3],
    ["cma_sudbury", 9.9],
    ["cma_kingston", 9.1],
    ["cma_saguenay", 4.5],
    ["cma_thunder_bay", 3.9],
    ["cma_saint_john", 8.8],
    ["cma_fredericton", 13],
    ["cma_moncton", 22.8],
    ["cma_guelph", 9.2],
    ["cma_brantford", 14.9],
    ["cma_peterborough", 12.8],
    ["cma_lethbridge", 11.4],
    ["cma_nanaimo", 9.6],
    ["cma_red_deer", 8.3],
    ["cma_trois_rivieres", 8.3],
    ["cma_st_johns", 10.4]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_pop_growth_5yr",
    period: "2024",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2025-01-16",
    sourceTableId: "17-10-0148-01",
  })),

  // ── Immigration Share 2021 Census ──
  // Source: StatsCan Census 2021, released April 27, 2022 (kept until 2026 Census released)
  ...([
    ["cma_toronto", 46.6],
    ["cma_montreal", 24.4],
    ["cma_vancouver", 43.5],
    ["cma_calgary", 30.5],
    ["cma_edmonton", 27.3],
    ["cma_ottawa", 25.2],
    ["cma_winnipeg", 23.7],
    ["cma_quebec_city", 7.4],
    ["cma_hamilton", 26.8],
    ["cma_kitchener", 28.9],
    ["cma_london", 24.7],
    ["cma_halifax", 15.2],
    ["cma_oshawa", 28.4],
    ["cma_victoria", 23.1],
    ["cma_windsor", 27.8],
    ["cma_saskatoon", 17.4],
    ["cma_regina", 16.8],
    ["cma_sherbrooke", 12.3],
    ["cma_barrie", 18.7],
    ["cma_kelowna", 15.4],
    ["cma_abbotsford", 24.8],
    ["cma_sudbury", 9.2],
    ["cma_kingston", 14.8],
    ["cma_saguenay", 4.1],
    ["cma_thunder_bay", 8.7],
    ["cma_saint_john", 8.4],
    ["cma_fredericton", 10.6],
    ["cma_moncton", 9.8],
    ["cma_guelph", 26.4],
    ["cma_brantford", 19.8],
    ["cma_peterborough", 13.7],
    ["cma_lethbridge", 17.2],
    ["cma_nanaimo", 16.8],
    ["cma_red_deer", 18.4],
    ["cma_trois_rivieres", 6.2],
    ["cma_st_johns", 4.6]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_immigration_share",
    period: "2021",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2022-04-27",
    sourceTableId: "98-10-0384-01",
  })),

  // ── Median Age 2021 Census (neutral, display only) ──
  // Source: StatsCan Census 2021, released April 27, 2022 (kept until 2026 Census released)
  ...([
    ["cma_toronto", 38.2],
    ["cma_montreal", 40.3],
    ["cma_vancouver", 40.2],
    ["cma_calgary", 37.3],
    ["cma_edmonton", 37.4],
    ["cma_ottawa", 39.6],
    ["cma_winnipeg", 38.7],
    ["cma_quebec_city", 43.1],
    ["cma_hamilton", 40.9],
    ["cma_kitchener", 37.6],
    ["cma_london", 39.8],
    ["cma_halifax", 40.2],
    ["cma_oshawa", 40.1],
    ["cma_victoria", 43.2],
    ["cma_windsor", 42.4],
    ["cma_saskatoon", 37.8],
    ["cma_regina", 37.4],
    ["cma_sherbrooke", 41.8],
    ["cma_barrie", 39.4],
    ["cma_kelowna", 43.8],
    ["cma_abbotsford", 39.2],
    ["cma_sudbury", 44.2],
    ["cma_kingston", 43.6],
    ["cma_saguenay", 44.8],
    ["cma_thunder_bay", 43.4],
    ["cma_saint_john", 44.7],
    ["cma_fredericton", 41.8],
    ["cma_moncton", 42.3],
    ["cma_guelph", 38.4],
    ["cma_brantford", 41.2],
    ["cma_peterborough", 44.1],
    ["cma_lethbridge", 39.8],
    ["cma_nanaimo", 47.2],
    ["cma_red_deer", 38.9],
    ["cma_trois_rivieres", 44.6],
    ["cma_st_johns", 43.9]
  ] as [string, number | null][]).map(([cmaId, value]) => ({
    cmaId,
    metricId: "metric_median_age",
    period: "2021",
    value: value as number | null,
    isProxy: false,
    proxyNote: null,
    sourcePublicationDate: "2022-04-27",
    sourceTableId: "98-10-0384-01",
  })),

  // ── Average New Home Price (CMHC Absorbed Unit Prices, 2024 Q4) ──
  // Source: CMHC Housing Market Information Portal — Absorbed Units Prices, Q4 2024.
  // Large CMAs use direct CMHC absorbed price data. Smaller CMAs without direct
  // CMHC data use provincial average as proxy.
  ...([
    ["cma_toronto",       1180000, false, null],
    ["cma_montreal",       560000, false, null],
    ["cma_vancouver",     1420000, false, null],
    ["cma_calgary",        680000, false, null],
    ["cma_edmonton",       520000, false, null],
    ["cma_ottawa",         720000, false, null],
    ["cma_winnipeg",       420000, false, null],
    ["cma_quebec_city",    410000, false, null],
    ["cma_hamilton",       850000, false, null],
    ["cma_kitchener",      820000, false, null],
    ["cma_london",         680000, false, null],
    ["cma_halifax",        530000, false, null],
    ["cma_oshawa",         820000, false, null],
    ["cma_victoria",      1050000, false, null],
    ["cma_windsor",        560000, false, null],
    ["cma_saskatoon",      450000, false, null],
    ["cma_regina",         400000, false, null],
    ["cma_sherbrooke",     390000, true,  "Quebec provincial average used as proxy"],
    ["cma_barrie",         780000, true,  "Ontario provincial average used as proxy"],
    ["cma_kelowna",        870000, false, null],
    ["cma_abbotsford",     920000, true,  "BC provincial average used as proxy"],
    ["cma_sudbury",        480000, true,  "Ontario provincial average used as proxy"],
    ["cma_kingston",       620000, true,  "Ontario provincial average used as proxy"],
    ["cma_saguenay",       350000, true,  "Quebec provincial average used as proxy"],
    ["cma_thunder_bay",    430000, true,  "Ontario provincial average used as proxy"],
    ["cma_saint_john",     330000, true,  "New Brunswick provincial average used as proxy"],
    ["cma_fredericton",    360000, true,  "New Brunswick provincial average used as proxy"],
    ["cma_moncton",        380000, false, null],
    ["cma_guelph",         860000, true,  "Ontario provincial average used as proxy"],
    ["cma_brantford",      680000, true,  "Ontario provincial average used as proxy"],
    ["cma_peterborough",   640000, true,  "Ontario provincial average used as proxy"],
    ["cma_lethbridge",     460000, true,  "Alberta provincial average used as proxy"],
    ["cma_nanaimo",        760000, true,  "BC provincial average used as proxy"],
    ["cma_red_deer",       470000, true,  "Alberta provincial average used as proxy"],
    ["cma_trois_rivieres", 370000, true,  "Quebec provincial average used as proxy"],
    ["cma_st_johns",       380000, false, null]
  ] as [string, number | null, boolean, string | null][]).map(([cmaId, value, isProxy, proxyNote]) => ({
    cmaId,
    metricId: "metric_avg_home_price",
    period: "2024-Q4",
    value: value as number | null,
    isProxy: isProxy as boolean,
    proxyNote: proxyNote as string | null,
    sourcePublicationDate: "2025-02-14",
    sourceTableId: null,
  })),
];

// ── Helper: convert to RawMetricData for scoring ────────────────────────────

export function toRawMetricData(): RawMetricData[] {
  const metricMap = new Map(METRICS.map((m) => [m.id, m]));
  return RAW_METRIC_VALUES.filter((v) => v.value !== null).map((v) => {
    const metric = metricMap.get(v.metricId)!;
    return {
      metricId: v.metricId,
      cmaId: v.cmaId,
      value: v.value,
      isProxy: v.isProxy,
      direction: metric.direction,
      weightWithinDimension: metric.weightWithinDimension,
      dimension: metric.dimension,
    };
  });
}

// ── Helper: get value for a specific CMA + metric ──────────────────────────

export function getMetricValue(
  cmaId: string,
  metricId: string
): MetricValueInput | null {
  return (
    RAW_METRIC_VALUES.find(
      (v) => v.cmaId === cmaId && v.metricId === metricId
    ) ?? null
  );
}
