/**
 * Historical metric data — auto-generated by scripts/backfill-history.ts
 * Generated: 2026-03-01T03:09:02.816Z
 * Total data points: 9210
 * DO NOT EDIT MANUALLY
 */

import rawHistory from "../../data/metric-history.json";

export interface HistoricalDataPoint {
  metricId: string;
  cmaId: string;
  period: string;
  value: number;
  isProxy: boolean;
  proxyNote: string | null;
  sourceTableId: string;
  collectedAt: string;
}

export const HISTORY: HistoricalDataPoint[] = rawHistory as HistoricalDataPoint[];

export function getMetricHistory(metricId: string, cmaId: string): HistoricalDataPoint[] {
  return HISTORY.filter((p) => p.metricId === metricId && p.cmaId === cmaId).sort((a, b) =>
    a.period.localeCompare(b.period),
  );
}

export function getLatestPeriod(metricId: string): string | null {
  const periods = HISTORY.filter((p) => p.metricId === metricId)
    .map((p) => p.period)
    .sort();
  return periods.length > 0 ? periods[periods.length - 1] : null;
}

export function getMetricPeriods(metricId: string): string[] {
  const seen = new Set<string>();
  const periods: string[] = [];
  for (const p of HISTORY) {
    if (p.metricId === metricId && !seen.has(p.period)) {
      seen.add(p.period);
      periods.push(p.period);
    }
  }
  return periods.sort();
}
